Startup Script
Starting attendance_scanner.py
Exception in thread lcd_loop:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/attendance-scanner/lcd_panel.py", line 19, in lcd_loop
    self.lcd = ILCDPanel()
  File "/home/pi/attendance-scanner/i_lcd_panel.py", line 7, in __init__
    self.adafruit_lcd = LCD.Adafruit_CharLCDPlate()
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_CharLCD-1.1.1-py3.5.egg/Adafruit_CharLCD/Adafruit_CharLCD.py", line 441, in __init__
    self._mcp = MCP.MCP23017(address=address, busnum=busnum)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/MCP230xx.py", line 153, in __init__
    super(MCP23017, self).__init__(address, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/MCP230xx.py", line 50, in __init__
    self.write_iodir()
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/MCP230xx.py", line 133, in write_iodir
    self._device.writeList(self.IODIR, self.iodir)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/I2C.py", line 129, in writeList
    self._bus.write_i2c_block_data(self._address, register, data)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO-0.2.3-py3.5.egg/Adafruit_PureIO/smbus.py", line 294, in write_i2c_block_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error

Running Attendance Scanner.
0
